// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	airdropRoundsFieldNames          = builder.RawFieldNames(&AirdropRounds{})
	airdropRoundsRows                = strings.Join(airdropRoundsFieldNames, ",")
	airdropRoundsRowsExpectAutoSet   = strings.Join(stringx.Remove(airdropRoundsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	airdropRoundsRowsWithPlaceHolder = strings.Join(stringx.Remove(airdropRoundsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	airdropRoundsModel interface {
		Insert(ctx context.Context, data *AirdropRounds) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AirdropRounds, error)
		Update(ctx context.Context, data *AirdropRounds) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAirdropRoundsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AirdropRounds struct {
		Id            uint64       `db:"id"`
		Name          string       `db:"name"`
		MerkleRoot    string       `db:"merkle_root"`
		TokenAddress  string       `db:"token_address"`
		ClaimDeadline time.Time    `db:"claim_deadline"`
		Status        string       `db:"status"`
		SnapshotAt    sql.NullTime `db:"snapshot_at"`
		CreatedAt     time.Time    `db:"created_at"`
	}
)

func newAirdropRoundsModel(conn sqlx.SqlConn) *defaultAirdropRoundsModel {
	return &defaultAirdropRoundsModel{
		conn:  conn,
		table: "`airdrop_rounds`",
	}
}

func (m *defaultAirdropRoundsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAirdropRoundsModel) FindOne(ctx context.Context, id uint64) (*AirdropRounds, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", airdropRoundsRows, m.table)
	var resp AirdropRounds
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAirdropRoundsModel) Insert(ctx context.Context, data *AirdropRounds) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, airdropRoundsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.MerkleRoot, data.TokenAddress, data.ClaimDeadline, data.Status, data.SnapshotAt)
	return ret, err
}

func (m *defaultAirdropRoundsModel) Update(ctx context.Context, data *AirdropRounds) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, airdropRoundsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.MerkleRoot, data.TokenAddress, data.ClaimDeadline, data.Status, data.SnapshotAt, data.Id)
	return err
}

func (m *defaultAirdropRoundsModel) tableName() string {
	return m.table
}
