// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	claimsFieldNames          = builder.RawFieldNames(&Claims{})
	claimsRows                = strings.Join(claimsFieldNames, ",")
	claimsRowsExpectAutoSet   = strings.Join(stringx.Remove(claimsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	claimsRowsWithPlaceHolder = strings.Join(stringx.Remove(claimsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	claimsModel interface {
		Insert(ctx context.Context, data *Claims) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Claims, error)
		FindOneByRoundIdWallet(ctx context.Context, roundId uint64, wallet string) (*Claims, error)
		Update(ctx context.Context, data *Claims) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultClaimsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Claims struct {
		Id        uint64         `db:"id"`
		RoundId   uint64         `db:"round_id"`
		UserId    uint64         `db:"user_id"`
		Wallet    string         `db:"wallet"`
		Amount    int64          `db:"amount"`
		TxHash    sql.NullString `db:"tx_hash"`
		Status    string         `db:"status"`
		ClaimedAt sql.NullTime   `db:"claimed_at"`
		CreatedAt time.Time      `db:"created_at"`
	}
)

func newClaimsModel(conn sqlx.SqlConn) *defaultClaimsModel {
	return &defaultClaimsModel{
		conn:  conn,
		table: "`claims`",
	}
}

func (m *defaultClaimsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultClaimsModel) FindOne(ctx context.Context, id uint64) (*Claims, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", claimsRows, m.table)
	var resp Claims
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClaimsModel) FindOneByRoundIdWallet(ctx context.Context, roundId uint64, wallet string) (*Claims, error) {
	var resp Claims
	query := fmt.Sprintf("select %s from %s where `round_id` = ? and `wallet` = ? limit 1", claimsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, roundId, wallet)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClaimsModel) Insert(ctx context.Context, data *Claims) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, claimsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoundId, data.UserId, data.Wallet, data.Amount, data.TxHash, data.Status, data.ClaimedAt)
	return ret, err
}

func (m *defaultClaimsModel) Update(ctx context.Context, newData *Claims) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, claimsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.RoundId, newData.UserId, newData.Wallet, newData.Amount, newData.TxHash, newData.Status, newData.ClaimedAt, newData.Id)
	return err
}

func (m *defaultClaimsModel) tableName() string {
	return m.table
}
