// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pointsLedgerFieldNames          = builder.RawFieldNames(&PointsLedger{})
	pointsLedgerRows                = strings.Join(pointsLedgerFieldNames, ",")
	pointsLedgerRowsExpectAutoSet   = strings.Join(stringx.Remove(pointsLedgerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	pointsLedgerRowsWithPlaceHolder = strings.Join(stringx.Remove(pointsLedgerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	pointsLedgerModel interface {
		Insert(ctx context.Context, data *PointsLedger) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*PointsLedger, error)
		Update(ctx context.Context, data *PointsLedger) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPointsLedgerModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PointsLedger struct {
		Id        uint64         `db:"id"`
		UserId    uint64         `db:"user_id"`
		Delta     int64          `db:"delta"`
		Reason    string         `db:"reason"`
		RefId     sql.NullInt64  `db:"ref_id"`
		Meta      sql.NullString `db:"meta"`
		CreatedAt time.Time      `db:"created_at"`
	}
)

func newPointsLedgerModel(conn sqlx.SqlConn) *defaultPointsLedgerModel {
	return &defaultPointsLedgerModel{
		conn:  conn,
		table: "`points_ledger`",
	}
}

func (m *defaultPointsLedgerModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPointsLedgerModel) FindOne(ctx context.Context, id uint64) (*PointsLedger, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pointsLedgerRows, m.table)
	var resp PointsLedger
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPointsLedgerModel) Insert(ctx context.Context, data *PointsLedger) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, pointsLedgerRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Delta, data.Reason, data.RefId, data.Meta)
	return ret, err
}

func (m *defaultPointsLedgerModel) Update(ctx context.Context, data *PointsLedger) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pointsLedgerRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Delta, data.Reason, data.RefId, data.Meta, data.Id)
	return err
}

func (m *defaultPointsLedgerModel) tableName() string {
	return m.table
}
