// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	roundPointsFieldNames          = builder.RawFieldNames(&RoundPoints{})
	roundPointsRows                = strings.Join(roundPointsFieldNames, ",")
	roundPointsRowsExpectAutoSet   = strings.Join(stringx.Remove(roundPointsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	roundPointsRowsWithPlaceHolder = strings.Join(stringx.Remove(roundPointsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	roundPointsModel interface {
		Insert(ctx context.Context, data *RoundPoints) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*RoundPoints, error)
		FindOneByRoundIdUserId(ctx context.Context, roundId uint64, userId uint64) (*RoundPoints, error)
		Update(ctx context.Context, data *RoundPoints) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultRoundPointsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RoundPoints struct {
		Id            uint64    `db:"id"`
		RoundId       uint64    `db:"round_id"`
		UserId        uint64    `db:"user_id"`
		Points        int64     `db:"points"`
		ClaimedPoints int64     `db:"claimed_points"`
		CreatedAt     time.Time `db:"created_at"`
	}
)

func newRoundPointsModel(conn sqlx.SqlConn) *defaultRoundPointsModel {
	return &defaultRoundPointsModel{
		conn:  conn,
		table: "`round_points`",
	}
}

func (m *defaultRoundPointsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRoundPointsModel) FindOne(ctx context.Context, id uint64) (*RoundPoints, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", roundPointsRows, m.table)
	var resp RoundPoints
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoundPointsModel) FindOneByRoundIdUserId(ctx context.Context, roundId uint64, userId uint64) (*RoundPoints, error) {
	var resp RoundPoints
	query := fmt.Sprintf("select %s from %s where `round_id` = ? and `user_id` = ? limit 1", roundPointsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, roundId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoundPointsModel) Insert(ctx context.Context, data *RoundPoints) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, roundPointsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoundId, data.UserId, data.Points, data.ClaimedPoints)
	return ret, err
}

func (m *defaultRoundPointsModel) Update(ctx context.Context, newData *RoundPoints) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, roundPointsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.RoundId, newData.UserId, newData.Points, newData.ClaimedPoints, newData.Id)
	return err
}

func (m *defaultRoundPointsModel) tableName() string {
	return m.table
}
