// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tasksFieldNames          = builder.RawFieldNames(&Tasks{})
	tasksRows                = strings.Join(tasksFieldNames, ",")
	tasksRowsExpectAutoSet   = strings.Join(stringx.Remove(tasksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tasksRowsWithPlaceHolder = strings.Join(stringx.Remove(tasksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tasksModel interface {
		Insert(ctx context.Context, data *Tasks) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Tasks, error)
		FindOneByCode(ctx context.Context, code string) (*Tasks, error)
		Update(ctx context.Context, data *Tasks) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTasksModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Tasks struct {
		Id          uint64         `db:"id"`
		Code        string         `db:"code"`
		Name        string         `db:"name"`
		Description sql.NullString `db:"description"`
		BasePoints  int64          `db:"base_points"`
		MaxPoints   sql.NullInt64  `db:"max_points"`
		Stackable   int64          `db:"stackable"`
		Metadata    sql.NullString `db:"metadata"`
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newTasksModel(conn sqlx.SqlConn) *defaultTasksModel {
	return &defaultTasksModel{
		conn:  conn,
		table: "`tasks`",
	}
}

func (m *defaultTasksModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTasksModel) FindOne(ctx context.Context, id uint64) (*Tasks, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tasksRows, m.table)
	var resp Tasks
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTasksModel) FindOneByCode(ctx context.Context, code string) (*Tasks, error) {
	var resp Tasks
	query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", tasksRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTasksModel) Insert(ctx context.Context, data *Tasks) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, tasksRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.Name, data.Description, data.BasePoints, data.MaxPoints, data.Stackable, data.Metadata)
	return ret, err
}

func (m *defaultTasksModel) Update(ctx context.Context, newData *Tasks) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tasksRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Code, newData.Name, newData.Description, newData.BasePoints, newData.MaxPoints, newData.Stackable, newData.Metadata, newData.Id)
	return err
}

func (m *defaultTasksModel) tableName() string {
	return m.table
}
