// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userTasksFieldNames          = builder.RawFieldNames(&UserTasks{})
	userTasksRows                = strings.Join(userTasksFieldNames, ",")
	userTasksRowsExpectAutoSet   = strings.Join(stringx.Remove(userTasksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userTasksRowsWithPlaceHolder = strings.Join(stringx.Remove(userTasksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userTasksModel interface {
		Insert(ctx context.Context, data *UserTasks) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserTasks, error)
		FindOneByUserIdTaskCodeUniqueKey(ctx context.Context, userId uint64, taskCode string, uniqueKey string) (*UserTasks, error)
		Update(ctx context.Context, data *UserTasks) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserTasksModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserTasks struct {
		Id        uint64    `db:"id"`
		UserId    uint64    `db:"user_id"`
		TaskCode  string    `db:"task_code"`
		Amount    int64     `db:"amount"`
		Points    int64     `db:"points"`
		UniqueKey string    `db:"unique_key"`
		CreatedAt time.Time `db:"created_at"`
	}
)

func newUserTasksModel(conn sqlx.SqlConn) *defaultUserTasksModel {
	return &defaultUserTasksModel{
		conn:  conn,
		table: "`user_tasks`",
	}
}

func (m *defaultUserTasksModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserTasksModel) FindOne(ctx context.Context, id uint64) (*UserTasks, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userTasksRows, m.table)
	var resp UserTasks
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTasksModel) FindOneByUserIdTaskCodeUniqueKey(ctx context.Context, userId uint64, taskCode string, uniqueKey string) (*UserTasks, error) {
	var resp UserTasks
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `task_code` = ? and `unique_key` = ? limit 1", userTasksRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, taskCode, uniqueKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTasksModel) Insert(ctx context.Context, data *UserTasks) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userTasksRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TaskCode, data.Amount, data.Points, data.UniqueKey)
	return ret, err
}

func (m *defaultUserTasksModel) Update(ctx context.Context, newData *UserTasks) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userTasksRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.TaskCode, newData.Amount, newData.Points, newData.UniqueKey, newData.Id)
	return err
}

func (m *defaultUserTasksModel) tableName() string {
	return m.table
}
