// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"airdrop/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/airdrop/snapshot",
				Handler: CreateSnapshotHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/airdrop/snapshot/:id",
				Handler: GetSnapshotHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/airdrop/snapshot/:id/proof",
				Handler: GetSnapshotProofHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tasks/login_streak",
				Handler: ReportLoginStreakHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tasks/promote",
				Handler: ReportPromoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tasks/quant_invest",
				Handler: ReportQuantInvestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tasks/referral",
				Handler: ReportReferralHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tasks/trade_volume",
				Handler: ReportTradeVolumeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users",
				Handler: CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:id",
				Handler: GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:id/score",
				Handler: GetUserScoreHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:id/tasks",
				Handler: GetUserTasksHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
