// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AwardTaskRequest struct {
	Wallet string `json:"wallet"`
	Task   string `json:"task"`
	Amount int64  `json:"amount"`
	Extra  string `json:"extra"`
}

type AwardTaskData struct {
	Points int64 `json:"points"`
}

type AwardTaskResponse struct {
	BaseResp
	Data AwardTaskData `json:"data"`
}

type BaseResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type ClaimRequest struct {
	RoundId int64    `json:"roundId"`
	Wallet  string   `json:"wallet"`
	Amount  int64    `json:"amount"`
	Proof   []string `json:"proof"`
}

type ClaimData struct {
	TxHash string `json:"txHash"`
	Status string `json:"status"`
}

type ClaimResponse struct {
	BaseResp
	Data ClaimData `json:"data"`
}

type LoginRequest struct {
	Wallet    string `json:"wallet"`
	Signature string `json:"signature"`
	Timestamp int64  `json:"timestamp"`
}

type LoginData struct {
	AccessToken string `json:"accessToken"`
	ExpiresAt   int64  `json:"expiresAt"`
	LoginDays   int64  `json:"loginDays"`
	Points      int64  `json:"points"`
}

type LoginResponse struct {
	BaseResp
	Data LoginData `json:"data"`
}

type PointsData struct {
	Wallet      string `json:"wallet"`
	Available   int64  `json:"available"`
	Frozen      int64  `json:"frozen"`
	LatestRound int64  `json:"latestRound"`
	LoginStreak int64  `json:"loginStreak"`
}

type PointsResponse struct {
	BaseResp
	Data PointsData `json:"data"`
}

type RoundInfoData struct {
	CurrentRoundId int64  `json:"currentRoundId"`
	RoundName      string `json:"roundName"`
	ClaimDeadline  int64  `json:"claimDeadline"`
	MerkleRoot     string `json:"merkleRoot"`
	TokenAddress   string `json:"tokenAddress"`
	TotalPoints    int64  `json:"totalPoints"`
}

type RoundInfoResponse struct {
	BaseResp
	Data RoundInfoData `json:"data"`
}

type StartRoundRequest struct {
	RoundName     string `json:"roundName"`
	MerkleRoot    string `json:"merkleRoot"`
	TokenAddress  string `json:"tokenAddress"`
	ClaimDeadline int64  `json:"claimDeadline"`
}
