// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"airdrop/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/admin/airdrop/round",
				Handler: RoundInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/admin/airdrop/start",
				Handler: StartRoundHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/admin/tasks/award",
				Handler: AwardTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/airdrop/claim",
				Handler: ClaimAirdropHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/airdrop/me/registration",
				Handler: RegistrationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/airdrop/task/submit",
				Handler: SubmitTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/me/points",
				Handler: GetPointsHandler(serverCtx),
			},
		},
	)
}
