// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type CreateSnapshotReq struct {
	Name         string `json:"name"`
	TokenAddress string `json:"token_address"`
}

type CreateSnapshotResp struct {
	BaseResp
	Data SnapshotInfo `json:"data"`
}

type CreateUserReq struct {
	WalletAddr string `json:"wallet_addr"`
	Nickname   string `json:"nickname,optional"`
}

type CreateUserResp struct {
	BaseResp
	Data UserInfo `json:"data"`
}

type GetProofReq struct {
	SnapshotId int64  `form:"snapshot_id"`
	Address    string `form:"address"`
}

type GetProofResp struct {
	BaseResp
	Data ProofData `json:"data"`
}

type GetSnapshotResp struct {
	BaseResp
	Data SnapshotInfo `json:"data"`
}

type GetUserData struct {
	User  UserInfo `json:"user"`
	Score int64    `json:"score"`
	Tier  string   `json:"tier"`
}

type GetUserResp struct {
	BaseResp
	Data GetUserData `json:"data"`
}

type ProofData struct {
	Address string   `json:"address"`
	Index   int64    `json:"index"`
	Amount  string   `json:"amount"`
	Proof   []string `json:"proof"`
}

type ReportTaskReq struct {
	UserId   int64  `json:"user_id"`
	Evidence string `json:"evidence,optional"` // 链接或截图说明
	Value    string `json:"value,optional"`    // 如交易量、金额等
}

type ScoreData struct {
	Score int64  `json:"score"`
	Tier  string `json:"tier"`
}

type ScoreResp struct {
	BaseResp
	Data ScoreData `json:"data"`
}

type SnapshotInfo struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	MerkleRoot   string `json:"merkle_root"`
	TokenAddress string `json:"token_address"`
	TotalUsers   int64  `json:"total_users"`
	TotalAmount  string `json:"total_amount"`
	Status       int64  `json:"status"`
}

type UserInfo struct {
	Id         int64  `json:"id"`
	WalletAddr string `json:"wallet_addr"`
	Nickname   string `json:"nickname,optional"`
}

type UserTaskItem struct {
	TaskId      int64  `json:"task_id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Status      int64  `json:"status"`
	CompletedAt string `json:"completed_at,optional"`
}

type UserTasksResp struct {
	BaseResp
	Data []UserTaskItem `json:"data"`
}
